// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/index.tsx";
import * as $1 from "./routes/products/[product].tsx";
import * as $$0 from "./islands/AddToCart.tsx";
import * as $$1 from "./islands/Cart.tsx";
import * as $$2 from "./islands/ProductDetails.tsx";

const manifest = {
  routes: {
    "./routes/index.tsx": $0,
    "./routes/products/[product].tsx": $1,
  },
  islands: {
    "./islands/AddToCart.tsx": $$0,
    "./islands/Cart.tsx": $$1,
    "./islands/ProductDetails.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
